### ISSUE TITLE
Reconsider IDE

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/python-for-everything#17]
- [ ] PyCharm
- [ ] Spyder
- [x] Jupyter
- [ ] Light Table

**Comment by deniederhut** [comment]
To quickly recap the discussion, Spyder was nice in that it is packaged with the Anaconda install, but it gets laggy on Mac OSX. Jupyter is popular with online materials, but may encourage bad coding habits. Light Table looks like a pretty nifty editor, but doesn't give us the combined text/console/objects/images of an IDE.

I'm not a big fan of PyCharm, but I would vote we try it for the May series.

@juanshishido @henchc @davclark ??

**Comment by davclark** [comment]
I was the one who chose PyCharm back in the day. I also don't love it, but at least it's 'alright' in many ways. It has poor integration with plotting as the biggest downside.

**Comment by henchc** [comment]
I'll play around with it next week, but you all seem to have prior experience with it, so I trust your judgement.

**Comment by davclark** [comment]
And FWIW, you are learning the basis of a whole ecosystem:

http://www.jetbrains.org/pages/viewpage.action?pageId=983889

On Wed, Apr 13, 2016 at 5:47 PM, Christopher Hench <notifications@github.com
> wrote:

> I'll play around with it next week, but you all seem to have prior
> experience with it, so I trust your judgement.
>
>
> > On Apr 13, 2016, at 17:24, Dav Clark <notifications@github.com> wrote:
> >
> > I was the one who chose PyCharm back in the day. I also don't love it,
> but at least it's 'alright' in many ways. It has poor integration with
> plotting as the biggest downside.
>
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dlab-berkeley/python-for-everything/issues/17#issuecomment-209702828>
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408

**Comment by rochelleterman** [comment]
Has this been settled yet? If anyone cares, my preference is for jupyter.

**Comment by deniederhut** [comment]
Sorry - I should have closed this.

We settled on PyCharm, but Jupyter was the runner up. The issues we discussed about Jupyter were:

1. Teaches bad coding habits
2. Will not work during the practice sessions (so we will need another editor or IDE anyway)
3. Represents small share of python ecosystem

**Comment by davclark** [comment]
[PyCharm supports jupyter notebooks since 2014](
http://blog.jetbrains.com/pycharm/2014/12/feature-spotlight-ipython-notebook-inside-an-ide/).
Could be a reasonable approach.

-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408
