### ISSUE TITLE
Day 02 Challenge A (HTML): Unit test assertion error

### ISSUE THREAD

**Issue by akokai** [dlab-berkeley/python-for-everything#22]
For the HTML parsing challenge, the unit test `test_header()` has a problematic assertion in [this line](https://github.com/dlab-berkeley/python-for-everything/blob/master/challenges/02_scraping/test_A.py#L21).
- The length of a string joining all those HTML tags is 90, not 17 (see [this gist](https://gist.github.com/akokai/448817ff80ee65d19ef11ae1befd6527)). Instead, 17 is the length of the list of tags before joining as a string.
- The variable that the unit test looks for is named slightly differently from the challenge ('head' versus 'header').

Solution:
- Change the assertion to `== 90` (or change the challenge to ask for a list instead of a string).
- Name both variables the same thing.

**Comment by deniederhut** [comment]
Closed in cb6d772d6f1b0fca89cf9870be58a1c6e19cf6e2
