### ISSUE TITLE
Instruction Format

### ISSUE THREAD

**Issue by rochelleterman** [dlab-berkeley/python-for-everything#24]
Hi all,

Apologies if this has already been discussed and I didn't take notice. I'm trying to prepare for teaching and need some guidelines to make it seamless for the students. Dillon, what are you planning for Day 0? Live coding with PyCharm? Are students cloning the github repo? Any guidance you have would be most appreciated.

Thanks, R

**Comment by deniederhut** [comment]
Sorry! We had a meeting about this last week, but I assumed you were already familiar with our process.

Workshops are split between interactive live-coding, and pair coding practice exercises implemented in pytest. The topics covered in each day, with background info and pre-worked examples, are in the instruction materials. I can also send you some meta-info around the python curriculum, but it's a tad out of date at this point. It might be easiest just to show up to the class the day before your own to get a feeling for how things run.

Everyone will get all of the materials at once on Monday, although some people may join later in the series.
